name: SBOM
on: workflow_dispatch

jobs:
  cyclone:
    name: 'Build'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 15.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test example
      working-directory: ./example
      run: |
        npm install
        npm run build --if-present
    - name: CycloneDX Node.js Generate SBOM
      uses: CycloneDX/gh-node-module-generatebom@v1.0.3
      with:
        path: ../../
        output: ./bom.xml
